services:
  backend:
    container_name: springboot-app
    build:
      context: ./Back
      dockerfile: app/Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/practica_db
      SPRING_DATASOURCE_USERNAME: usuario1
      SPRING_DATASOURCE_PASSWORD: contraseña
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: practica_db
      POSTGRES_USER: usuario1
      POSTGRES_PASSWORD: contraseña
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U usuario1 -d practica_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: ./front/frontend
      dockerfile: Dockerfile
    container_name: nginx_app
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
